### ISSUE TITLE
Update dependencies to the latest spatie/laravel-medialibrary revision 9.x

### ISSUE THREAD

**Issue by vrusua** [shortcodes/media#3]
@shortcodes 

Hi Roman,

is there any chance to make the package compatible with the actual spatie/laravel-medialibrary revision (>9.7), or?

Thanks,
Ruslan

**Comment by shortcodes** [comment]
Hi. I need to think about it. Need to check if current version of
spatie/medialibrary is sufficent (does my package is obsolete). I try to do
this next week.

śr., 11 sie 2021 o 11:25 Ruslan Voroshchuk ***@***.***>
napisał(a):

**Comment by shortcodes** [comment]
@vrusua I updated dependencies to newest spatie/medial-library. Hope it would will solve your issue!
